
"use client";

import { useStyleProfile } from '@/hooks/useStyleProfile';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Wand2 } from 'lucide-react';

export default function ProfilePage() {
  const [styleProfile] = useStyleProfile();

  return (
    <div className="container mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <Card className="shadow-2xl backdrop-blur-sm bg-card/80 border-primary/10">
          <CardHeader className="text-center items-center flex flex-col">
            <div className="p-3 bg-primary/10 rounded-full mb-4">
              <Wand2 className="h-10 w-10 text-primary" />
            </div>
            <CardTitle className="text-4xl font-headline tracking-wider">Your Style Profile</CardTitle>
            <CardDescription className="text-lg">
              This profile is automatically generated by our AI based on the outfits you analyze.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="mt-6 p-6 border rounded-lg bg-background/80">
              <p className="text-foreground/80 leading-relaxed text-center whitespace-pre-wrap">
                {styleProfile}
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
